services:
  neo4j:
    image: neo4j:5.15
    container_name: metastate-neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-neo4j}
    volumes:
      - neo4j_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "cypher-shell -u neo4j -p ${NEO4J_PASSWORD:-neo4j} 'RETURN 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  neo4j_data:

