packages:
  - apps/*
  - packages/*
  - platforms/*
  - infrastructure/*
  - tests/
  - docs/
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@rollup/rollup-linux-x64-gnu'
  - cpu-features
  - esbuild
  - msw
  - protobufjs
  - rollup
  - ssh2
  - svelte-preprocess
