packages:
  - apps/*
  - packages/*
  - platforms/*
  - infrastructure/*
  - tests/
onlyBuiltDependencies:
  - '@biomejs/biome'
  - cpu-features
  - esbuild
  - msw
  - protobufjs
  - ssh2
  - svelte-preprocess
