packages:
    - platforms/*
    - apps/*
    - packages/*
    - platforms/*/*
    - infrastructure/*
    - services/*
    - notification-trigger
    - tests/
    - docs/
onlyBuiltDependencies:
    - "@biomejs/biome"
    - "@rollup/rollup-linux-x64-gnu"
    - cpu-features
    - esbuild
    - msw
    - protobufjs
    - rollup
    - ssh2
    - svelte-preprocess
