packages:
  - apps/*
  - packages/*
  - platforms/*
  - infrastructure/*
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@tailwindcss/oxide'
  - cpu-features
  - esbuild
  - msw
  - protobufjs
  - ssh2
  - svelte-preprocess
  - unrs-resolver
