/**
 * Client secret verification. Every secret is generated by the connector
 * with 256 bits of entropy and stored as `sha256:<hex>`: a slow hash buys
 * nothing against guessing a random 256-bit value. Comparisons are
 * constant-time.
 */

import { createHash, timingSafeEqual } from "node:crypto";

function parseHash(stored: string): Buffer | null {
    const match = /^sha256:([0-9a-f]{64})$/i.exec(stored);
    return match ? Buffer.from(match[1], "hex") : null;
}

/** True if `stored` is a hash this module can verify. */
export function isSupportedHash(stored: string): boolean {
    return parseHash(stored) !== null;
}

export async function verifySecret(
    secret: string,
    stored: string,
): Promise<boolean> {
    const digest = parseHash(stored);
    if (!digest) return false;
    const candidate = createHash("sha256").update(secret, "utf8").digest();
    return timingSafeEqual(candidate, digest);
}

/**
 * A hash no secret matches, checked when the client ID is unknown so a failed
 * lookup costs the same as a wrong secret and response times do not reveal
 * which client IDs exist.
 */
export const DUMMY_HASH = `sha256:${"0".repeat(64)}`;
