import { MigrationInterface, QueryRunner } from "typeorm";

export class SecurityAnswerAttempt1779517729310 implements MigrationInterface {
    name = 'SecurityAnswerAttempt1779517729310'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // device_token: rename the legacy unique constraint index to the
        // TypeORM-generated name. Use IF EXISTS so re-running on a partially
        // migrated DB doesn't bail out.
        await queryRunner.query(
            `DROP INDEX IF EXISTS "public"."UQ_device_token_ename"`,
        );

        await queryRunner.query(
            `CREATE TABLE "security_answer_attempt" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eName" character varying NOT NULL, "failedCount" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP, "lastAttemptAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_216170eabe6bbbc36d97f20c7f9" PRIMARY KEY ("id"))`,
        );
        await queryRunner.query(
            `CREATE UNIQUE INDEX "IDX_372fc1eef6d4fcc2f181b15fbc" ON "security_answer_attempt" ("eName") `,
        );

        // notifications.body: widen `character varying` → `text` in-place
        // instead of DROP COLUMN + ADD COLUMN NOT NULL. The autogenerated
        // drop-and-add destroys existing rows' body data and then fails the
        // NOT NULL constraint because the freshly-added column is null for
        // every existing row. Backfill any pre-existing nulls with '' first
        // so the NOT NULL re-application succeeds on dirty data too.
        await queryRunner.query(
            `UPDATE "notifications" SET "body" = '' WHERE "body" IS NULL`,
        );
        await queryRunner.query(
            `ALTER TABLE "notifications" ALTER COLUMN "body" TYPE text USING "body"::text`,
        );
        await queryRunner.query(
            `ALTER TABLE "notifications" ALTER COLUMN "body" SET NOT NULL`,
        );

        await queryRunner.query(
            `CREATE UNIQUE INDEX IF NOT EXISTS "IDX_6c2242ce617f6bff7b5dfab565" ON "device_token" ("eName") `,
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            `DROP INDEX IF EXISTS "public"."IDX_6c2242ce617f6bff7b5dfab565"`,
        );
        // Mirror the up: in-place narrow back to varchar, preserve data.
        await queryRunner.query(
            `ALTER TABLE "notifications" ALTER COLUMN "body" TYPE character varying USING "body"::character varying`,
        );
        await queryRunner.query(
            `DROP INDEX IF EXISTS "public"."IDX_372fc1eef6d4fcc2f181b15fbc"`,
        );
        await queryRunner.query(`DROP TABLE "security_answer_attempt"`);
        await queryRunner.query(
            `CREATE UNIQUE INDEX "UQ_device_token_ename" ON "device_token" ("eName") `,
        );
    }

}
