/**
 * Neo4j Migration: Add point-lookup indexes on Envelope.id and MetaEnvelope.id
 *
 * Without these, every `MATCH (e:Envelope { id: $id })` and
 * `MATCH (m:MetaEnvelope { id: $id })` does a NodeByLabelScan over the entire
 * Envelope / MetaEnvelope population, which scales linearly with total stored
 * data. Update operations call these queries once per payload field, so a
 * 5-field chat update can take 10+ seconds.
 *
 * `id` is generated by W3IDBuilder and is unique by construction, so a plain
 * range index on the property is sufficient — no need for a composite index
 * with eName, since the id alone is selective.
 */

import type { Driver } from "neo4j-driver";

const STATEMENTS: { name: string; cypher: string }[] = [
    {
        name: "envelope_id_index",
        cypher: `CREATE INDEX envelope_id_index IF NOT EXISTS FOR (e:Envelope) ON (e.id)`,
    },
    {
        name: "meta_envelope_id_index",
        cypher: `CREATE INDEX meta_envelope_id_index IF NOT EXISTS FOR (m:MetaEnvelope) ON (m.id)`,
    },
];

export async function createIdIndexes(driver: Driver): Promise<void> {
    const session = driver.session();
    try {
        for (const { name, cypher } of STATEMENTS) {
            try {
                await session.run(cypher);
                console.log(`Ensured ${name}`);
            } catch (error) {
                if (
                    error instanceof Error &&
                    error.message.includes("already exists")
                ) {
                    console.log(`${name} already exists`);
                } else {
                    console.error(`Error creating ${name}:`, error);
                    throw error;
                }
            }
        }
    } finally {
        await session.close();
    }
}
