version: '3.8'

services:
  evault:
    build:
      context: ../../
      dockerfile: ./infrastructure/evault-core/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    networks: 
      - graphnet
    depends_on:
      - neo4j
    develop:
      watch:
        - action: sync
          path: ./          
          target: /app/infrastructure/evault-core
          ignore:
            - node_modules
        - action: rebuild
          path: ./package.json
        - action: rebuild
          path: ./.env

  neo4j:
    image: neo4j:5.15
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - graphnet

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  graphnet:
    driver: bridge
