name: Tests [W3ID]

on:
  push:
    branches: [main]
    paths:
      - 'infrastructure/w3id/**'
  pull_request:
    branches: [main]
    paths:
      - 'infrastructure/w3id/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm -F=w3id test

